// constants/permissions.js
import { ROLES } from './roles';

export const PERMISSIONS = {
  // Admin
  MANAGE_DEPARTMENTS: 'MANAGE_DEPARTMENTS',
  MANAGE_ASSET_CATEGORIES: 'MANAGE_ASSET_CATEGORIES',
  MANAGE_AUDIT_CYCLES: 'MANAGE_AUDIT_CYCLES',
  MANAGE_EMPLOYEES_ROLES: 'MANAGE_EMPLOYEES_ROLES',
  VIEW_ORG_ANALYTICS: 'VIEW_ORG_ANALYTICS',

  // Asset Manager
  REGISTER_ASSET: 'REGISTER_ASSET',
  ALLOCATE_ASSET: 'ALLOCATE_ASSET',
  APPROVE_TRANSFER: 'APPROVE_TRANSFER', 
  APPROVE_MAINTENANCE: 'APPROVE_MAINTENANCE',
  RESOLVE_AUDIT_DISCREPANCY: 'RESOLVE_AUDIT_DISCREPANCY',
  APPROVE_RETURN: 'APPROVE_RETURN',

  // Department Head
  VIEW_DEPT_ASSETS: 'VIEW_DEPT_ASSETS',
  APPROVE_DEPT_TRANSFER: 'APPROVE_DEPT_TRANSFER',
  BOOK_DEPT_RESOURCE: 'BOOK_DEPT_RESOURCE',

  // Employee
  VIEW_OWN_ASSETS: 'VIEW_OWN_ASSETS',
  BOOK_RESOURCE: 'BOOK_RESOURCE',
  RAISE_MAINTENANCE: 'RAISE_MAINTENANCE',
  INITIATE_RETURN_TRANSFER: 'INITIATE_RETURN_TRANSFER',
};

// Map each role to their explicit permissions based on the docs
export const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: [
    PERMISSIONS.MANAGE_DEPARTMENTS,
    PERMISSIONS.MANAGE_ASSET_CATEGORIES,
    PERMISSIONS.MANAGE_AUDIT_CYCLES,
    PERMISSIONS.MANAGE_EMPLOYEES_ROLES,
    PERMISSIONS.VIEW_ORG_ANALYTICS,
  ],
  [ROLES.ASSET_MANAGER]: [
    PERMISSIONS.REGISTER_ASSET,
    PERMISSIONS.ALLOCATE_ASSET,
    PERMISSIONS.APPROVE_TRANSFER,
    PERMISSIONS.APPROVE_MAINTENANCE,
    PERMISSIONS.RESOLVE_AUDIT_DISCREPANCY,
    PERMISSIONS.APPROVE_RETURN,
    
    // Inherits employee capabilities
    PERMISSIONS.VIEW_OWN_ASSETS,
    PERMISSIONS.BOOK_RESOURCE,
    PERMISSIONS.RAISE_MAINTENANCE,
    PERMISSIONS.INITIATE_RETURN_TRANSFER,
  ],
  [ROLES.DEPT_HEAD]: [
    PERMISSIONS.VIEW_DEPT_ASSETS,
    PERMISSIONS.APPROVE_DEPT_TRANSFER,
    PERMISSIONS.BOOK_DEPT_RESOURCE,
    
    // Inherits employee capabilities
    PERMISSIONS.VIEW_OWN_ASSETS,
    PERMISSIONS.BOOK_RESOURCE,
    PERMISSIONS.RAISE_MAINTENANCE,
    PERMISSIONS.INITIATE_RETURN_TRANSFER,
  ],
  [ROLES.EMPLOYEE]: [
    PERMISSIONS.VIEW_OWN_ASSETS,
    PERMISSIONS.BOOK_RESOURCE,
    PERMISSIONS.RAISE_MAINTENANCE,
    PERMISSIONS.INITIATE_RETURN_TRANSFER,
  ],
};
